---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
- name: workshop-pipelines

params:
  CF_API_URI:
  CF_USERNAME: 
  CF_PASSWORD:
  ORG:
  INSTANCES:

run:
  path: pcf-workshop-dev/tools/pipeline/tasks/scale-back-app.sh
