---
resources:
- name: workshop-web-app
  type: git
  source:
    uri: git@github.com:sapient007/pcf-workshop-dev.git
    private_key: {{git_private_key}}
    branch: {{workshop-branch}}

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf_api_uri}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_organization}}
    space: {{cf_space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: workshop-web-app, trigger: true}
  - put: resource-deploy-web-app
    params:
      manifest: workshop-web-app/workshop_assets/manifest.yml
      path: workshop-web-app/workshop_assets/
