---
resources:
- name: pcf-workshop-dev
  type: git
  source:
    uri: git@github.com:sapient007/pcf-workshop-dev.git
    private_key: {{git_private_key}}
    ignore_paths: pcf-workshop-dev/tools
    branch: {{workshop-branch}}

jobs:
- name: job-scale-app
  serial: true
  plan:
  - aggregate:
    - get: pcf-workshop-dev
  - task: scale-back-apps
    file: pcf-workshop-dev/tools/pipeline/tasks/scale-app.yml
    params:
        CF_API_URI: {{cf_api_uri}}
        CF_USERNAME: {{cf_user}}
        CF_PASSWORD: {{cf_password}}
        ORG: {{cf_organization}}
        INSTANCES: {{application_instances}}
